# Generated by Django 4.2.14 on 2025-12-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.CharField(choices=[('admin', '管理者'), ('operator', 'オペレーター')], default='operator', max_length=20, verbose_name='権限'),
        ),
    ]
