# Generated by Django 4.2.14 on 2025-12-19 04:55

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMeter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('meter_id', models.CharField(db_index=True, max_length=20, verbose_name='メーターID')),
                ('status', models.CharField(choices=[('registered', '登録済み'), ('active', '稼働中'), ('inactive', '停止中'), ('offline', 'オフライン')], default='registered', max_length=20, verbose_name='ステータス')),
                ('registered_at', models.DateTimeField(blank=True, editable=False, verbose_name='登録日時')),
                ('last_received_at', models.DateTimeField(blank=True, null=True, verbose_name='最終受信日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical メーター',
                'verbose_name_plural': 'historical メーター',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMeterAssignment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('project_id', models.IntegerField(verbose_name='案件ID')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical メーター紐付け',
                'verbose_name_plural': 'historical メーター紐付け',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(max_length=20, unique=True, verbose_name='メーターID')),
                ('status', models.CharField(choices=[('registered', '登録済み'), ('active', '稼働中'), ('inactive', '停止中'), ('offline', 'オフライン')], default='registered', max_length=20, verbose_name='ステータス')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('last_received_at', models.DateTimeField(blank=True, null=True, verbose_name='最終受信日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'メーター',
                'verbose_name_plural': 'メーター',
                'db_table': 'meters',
            },
        ),
        migrations.CreateModel(
            name='MeterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(verbose_name='案件ID')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='meters.meter', verbose_name='メーター')),
            ],
            options={
                'verbose_name': 'メーター紐付け',
                'verbose_name_plural': 'メーター紐付け',
                'db_table': 'meter_assignments',
            },
        ),
    ]
