# Generated by Django 4.2.14 on 2025-12-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmeter',
            name='b_route_enabled',
            field=models.BooleanField(default=True, verbose_name='Bルート有効'),
        ),
        migrations.AddField(
            model_name='historicalmeter',
            name='b_route_id',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='BルートID'),
        ),
        migrations.AddField(
            model_name='historicalmeter',
            name='b_route_password',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='Bルートパスワード'),
        ),
        migrations.AddField(
            model_name='historicalmeter',
            name='installed_at',
            field=models.DateField(blank=True, null=True, verbose_name='設置日'),
        ),
        migrations.AddField(
            model_name='meter',
            name='b_route_enabled',
            field=models.BooleanField(default=True, verbose_name='Bルート有効'),
        ),
        migrations.AddField(
            model_name='meter',
            name='b_route_id',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='BルートID'),
        ),
        migrations.AddField(
            model_name='meter',
            name='b_route_password',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='Bルートパスワード'),
        ),
        migrations.AddField(
            model_name='meter',
            name='installed_at',
            field=models.DateField(blank=True, null=True, verbose_name='設置日'),
        ),
        migrations.AlterField(
            model_name='historicalmeter',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='初回登録日時'),
        ),
        migrations.AlterField(
            model_name='historicalmeter',
            name='status',
            field=models.CharField(choices=[('inactive', '未稼働'), ('pending', '登録待ち'), ('active', '稼働中'), ('error', 'エラー')], default='inactive', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='初回登録日時'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='status',
            field=models.CharField(choices=[('inactive', '未稼働'), ('pending', '登録待ち'), ('active', '稼働中'), ('error', 'エラー')], default='inactive', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AddIndex(
            model_name='meterassignment',
            index=models.Index(fields=['meter', 'end_date'], name='meter_assig_meter_i_edd1ee_idx'),
        ),
        migrations.AddIndex(
            model_name='meterassignment',
            index=models.Index(fields=['project_id'], name='meter_assig_project_339ace_idx'),
        ),
    ]
