# Generated by Django 4.2.14 on 2025-12-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0003_historicalmeter_b_route_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmeterassignment',
            name='base_billing_day',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='基準検針日'),
        ),
        migrations.AddField(
            model_name='historicalmeterassignment',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='案件名'),
        ),
        migrations.AddField(
            model_name='historicalmeterassignment',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最終同期日時'),
        ),
        migrations.AddField(
            model_name='historicalmeterassignment',
            name='zone',
            field=models.IntegerField(blank=True, choices=[(0, '未設定'), (1, '北海道電力管轄'), (2, '東北電力管轄'), (3, '東京電力管轄'), (4, '中部電力管轄'), (5, '北陸電力管轄'), (6, '関西電力管轄'), (7, '中国電力管轄'), (8, '四国電力管轄'), (9, '九州電力管轄'), (10, '沖縄電力管轄')], null=True, verbose_name='電力管轄'),
        ),
        migrations.AddField(
            model_name='meterassignment',
            name='base_billing_day',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='基準検針日'),
        ),
        migrations.AddField(
            model_name='meterassignment',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='案件名'),
        ),
        migrations.AddField(
            model_name='meterassignment',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最終同期日時'),
        ),
        migrations.AddField(
            model_name='meterassignment',
            name='zone',
            field=models.IntegerField(blank=True, choices=[(0, '未設定'), (1, '北海道電力管轄'), (2, '東北電力管轄'), (3, '東京電力管轄'), (4, '中部電力管轄'), (5, '北陸電力管轄'), (6, '関西電力管轄'), (7, '中国電力管轄'), (8, '四国電力管轄'), (9, '九州電力管轄'), (10, '沖縄電力管轄')], null=True, verbose_name='電力管轄'),
        ),
        migrations.AddIndex(
            model_name='meterassignment',
            index=models.Index(fields=['zone', 'base_billing_day'], name='meter_assig_zone_9a349a_idx'),
        ),
    ]
