# Generated by Django 4.2.14 on 2026-03-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0004_historicalmeterassignment_base_billing_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmeterassignment',
            name='contract_capacity',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='PV容量(kW)'),
        ),
        migrations.AddField(
            model_name='meterassignment',
            name='contract_capacity',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='PV容量(kW)'),
        ),
    ]
