# Generated by Django 4.2.14 on 2026-05-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0005_historicalmeterassignment_contract_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmeterassignment',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='meterassignment',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='開始日'),
        ),
    ]
