# Generated by Django 4.2.14 on 2025-12-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmeterkey',
            name='key_version',
            field=models.IntegerField(default=1, verbose_name='鍵バージョン'),
        ),
        migrations.AddField(
            model_name='historicalmeterkey',
            name='last_key_exchange',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最終鍵交換日時'),
        ),
        migrations.AddField(
            model_name='historicalmeterkey',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='初回鍵交換日時'),
        ),
        migrations.AddField(
            model_name='meterkey',
            name='key_version',
            field=models.IntegerField(default=1, verbose_name='鍵バージョン'),
        ),
        migrations.AddField(
            model_name='meterkey',
            name='last_key_exchange',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最終鍵交換日時'),
        ),
        migrations.AddField(
            model_name='meterkey',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='初回鍵交換日時'),
        ),
    ]
