# Generated by Django 4.2.14 on 2025-12-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.IntegerField(choices=[(0, '未設定'), (1, '北海道電力管轄'), (2, '東北電力管轄'), (3, '東京電力管轄'), (4, '中部電力管轄'), (5, '北陸電力管轄'), (6, '関西電力管轄'), (7, '中国電力管轄'), (8, '四国電力管轄'), (9, '九州電力管轄'), (10, '沖縄電力管轄')], verbose_name='電力管轄')),
                ('fiscal_year', models.IntegerField(verbose_name='年度')),
                ('base_billing_day', models.CharField(max_length=2, verbose_name='基準検針日')),
                ('month', models.IntegerField(verbose_name='月')),
                ('actual_billing_date', models.DateField(verbose_name='実検針日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '検針日カレンダー',
                'verbose_name_plural': '検針日カレンダー',
                'db_table': 'billing_calendars',
                'indexes': [models.Index(fields=['zone', 'fiscal_year', 'base_billing_day'], name='billing_cal_zone_0963c7_idx'), models.Index(fields=['actual_billing_date'], name='billing_cal_actual__9d7e54_idx')],
                'unique_together': {('zone', 'fiscal_year', 'base_billing_day', 'month')},
            },
        ),
    ]
