# Generated by Django 4.2.14 on 2025-12-25 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0004_historicalmeterassignment_base_billing_day_and_more'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(verbose_name='案件ID')),
                ('project_name', models.CharField(blank=True, default='', max_length=200, verbose_name='案件名')),
                ('zone', models.IntegerField(choices=[(0, '未設定'), (1, '北海道電力管轄'), (2, '東北電力管轄'), (3, '東京電力管轄'), (4, '中部電力管轄'), (5, '北陸電力管轄'), (6, '関西電力管轄'), (7, '中国電力管轄'), (8, '四国電力管轄'), (9, '九州電力管轄'), (10, '沖縄電力管轄')], verbose_name='電力管轄')),
                ('base_billing_day', models.CharField(max_length=2, verbose_name='基準検針日')),
                ('period_start', models.DateField(verbose_name='検針開始日')),
                ('period_end', models.DateField(verbose_name='検針終了日')),
                ('import_start', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='発電累計開始')),
                ('import_end', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='発電累計終了')),
                ('route_b_export_start', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='売電累計開始')),
                ('route_b_export_end', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='売電累計終了')),
                ('generation_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='発電量(kWh)')),
                ('sold_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='売電量(kWh)')),
                ('self_consumption_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='自家消費量(kWh)')),
                ('status', models.CharField(choices=[('pending', '集計待ち'), ('draft', '仮確定'), ('confirmed', '確定')], default='pending', max_length=20, verbose_name='ステータス')),
                ('data_missing', models.BooleanField(default=False, verbose_name='データ欠損')),
                ('note', models.TextField(blank=True, default='', verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_summaries', to='meters.meter', verbose_name='メーター')),
            ],
            options={
                'verbose_name': '請求集計',
                'verbose_name_plural': '請求集計',
                'db_table': 'billing_summaries',
                'indexes': [models.Index(fields=['project_id'], name='billing_sum_project_1f10a0_idx'), models.Index(fields=['status'], name='billing_sum_status_be5f39_idx'), models.Index(fields=['period_end'], name='billing_sum_period__f8c7b7_idx')],
                'unique_together': {('meter', 'period_start', 'period_end')},
            },
        ),
    ]
