# Generated by Django 4.2.14 on 2026-03-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingsummary',
            name='curr_used_value',
        ),
        migrations.RemoveField(
            model_name='billingsummary',
            name='prev_used_value',
        ),
        migrations.AddField(
            model_name='billingsummary',
            name='curr_used_export',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='今回売電量累積値'),
        ),
        migrations.AddField(
            model_name='billingsummary',
            name='curr_used_import',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='今回発電量累積値'),
        ),
        migrations.AddField(
            model_name='billingsummary',
            name='prev_used_export',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='前回売電量累積値'),
        ),
        migrations.AddField(
            model_name='billingsummary',
            name='prev_used_import',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='前回発電量累積値'),
        ),
    ]
