# Generated by Django 4.2.14 on 2026-03-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_billingsummary_curr_used_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsummary',
            name='deemed_adjustment_kwh',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='みなし調整kWh'),
        ),
    ]
