# Generated by Django 4.2.14 on 2025-12-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingsummary'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='billingsummary',
            name='billing_sum_status_be5f39_idx',
        ),
        migrations.RemoveField(
            model_name='billingsummary',
            name='status',
        ),
        migrations.AddIndex(
            model_name='billingsummary',
            index=models.Index(fields=['zone', 'period_end'], name='billing_sum_zone_ef88f0_idx'),
        ),
    ]
