# Generated by Django 4.2.14 on 2025-12-23 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_billingsummary_meterevent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingSummary',
        ),
    ]
