# Generated by Django 4.2.14 on 2025-12-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('communication', '通信途絶'), ('data_missing', 'データ欠損'), ('anomaly', '異常値')], max_length=20, verbose_name='種別')),
                ('status', models.CharField(choices=[('open', '未対応'), ('acknowledged', '確認済'), ('resolved', '解決済')], default='open', max_length=20, verbose_name='ステータス')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='検知日時')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解決日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'アラート',
                'verbose_name_plural': 'アラート',
                'db_table': 'alerts',
            },
        ),
    ]
