# Generated by Django 4.2.14 on 2026-03-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('communication', '通信途絶'), ('anomaly', '異常値')], max_length=20, verbose_name='種別'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('open', '発生中'), ('resolved', '解決済')], default='open', max_length=20, verbose_name='ステータス'),
        ),
    ]
